### ISSUE TITLE
Tao 0.30.8 webview.set_size does nothing

### ISSUE THREAD

**Issue by Elendiar** [tauri-apps/tao#1020]
**Describe the bug**
After cargo update notice that `set_size` does nothing with ok result. Application popover window `set_size` when different popover called, but they always have same size.

Only one dependency override fix this.
```
[patch.crates-io]
tao = { git = 'https://github.com/tauri-apps/tao.git', tag = "tao-v0.30.6" }
```

<details>
  <summary>Cargo.toml dependencies</summary>
   
  ```toml
[dev-dependencies]
tauri-plugin-devtools = "2.0.0"

[dependencies]
base64 = "0.22.1"
debounced = "0.2.0"
dotenvy = "0.15.7"
dotenvy_macro = "0.15.7"
futures = "0.3.31"
log = "0.4.22"
regex = "1.11.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
shlex = "1.3.0"
specta = "2.0.0-rc.20"
specta-typescript = "0.0.7"
sysinfo = "0.32.0"
tauri-plugin-autostart = "2.0.1"
tauri-plugin-log = "2.0.2"
tauri-plugin-notification = "2.0.1"
tauri-plugin-process = "2.0.1"
tauri-plugin-shell = "2.0.2"
tauri-plugin-single-instance = "2.0.1"
tauri-plugin-store = "2.1.0"
tauri-plugin-updater = "2.0.2"
tauri-plugin-window-state = "2.0.2"
tauri-specta = { version = "2.0.0-rc.20", features = ["typescript", "derive"] }
tokio = { version = "1.41.1", features = ["time", "full"] }
xcap = "0.0.14"

[dependencies.tauri]
features = ["isolation", "devtools"]
version = "2.1.1"

[dependencies.windows]
features = [
  "Win32_Graphics_Dwm",
  "Win32_Graphics_Gdi",
  "Win32_System_Threading",
  "Win32_UI_Accessibility",
  "Win32_UI_HiDpi",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_Shell_Common",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging",
]
version = "0.58.0"

[build-dependencies]
tauri-build = { version = "2.0.3", features = ["isolation"] }

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
  ```

</details>

**Screenshots**
<img width="400" alt="image" src="https://github.com/user-attachments/assets/931a8401-6765-4ddf-a2f7-6d3256b0d65e">

**Platform and Versions (please complete the following information):**
OS: Windows 11
Rustc: rustc 1.84.0-nightly (03ee48451 2024-11-18)
