### ISSUE TITLE
Variable dragging room according to DPI scaling factor when resizing frameless window

### ISSUE THREAD

**Issue by idlist** [tauri-apps/tao#376]
Related to [tauri#3040](https://github.com/tauri-apps/tauri/issues/3040)

I'm using a '13 Windows laptop with 4k resolution (3840*2400 in detail) and I currently set the DPI scaling to 250%. Current room for resizing is like only half or even 1/3 of a framed window.

I feel like that simply increasing the resizing border in pixel does not solve the problem. I agree that it would be better if the room could be variable according to the DPI scaling factor.

**Comment by amrbashir** [comment]
Can you test if #379 fixes this for you?
in a tauri project where you have a borderless window: 
1. add this to you `src-tauri/Cargo.toml`
	```toml
	[patch.crates-io]
	tao = {git = "https://github.com/tauri-apps/tao", branch = "fix/scaled-resiznig-handlers"}
	```
2. run `cargo update` inside `src-tauri`
